#!/usr/bin/env python3
"""Write the synthetic mailbox and, from the same values, its ground truth.

Nothing here is real. The senders are all under `.example`, which is reserved
by RFC 2606 and can never be a live domain; the names, subjects, amounts and
attachment contents are invented; and the attachments are generated byte by
byte rather than copied from anywhere.

The point of generating the ground truth here rather than recording what the
tool produced is that `tests/expected.json` then describes the *mailbox*. A
test that asserts against it is asking "did the reader read this message
correctly", not "does the reader still agree with itself".

    python fixtures/generate_mailbox.py

Deterministic: same bytes every run, including the multipart boundaries and
the random-looking file contents, so regenerating the fixture is a no-op in
git unless something here actually changed.
"""

from __future__ import annotations

import email.policy
import hashlib
import json
import random
import struct
import zlib
from dataclasses import dataclass, field
from email.message import EmailMessage
from email.utils import parsedate_to_datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAILBOX = ROOT / "fixtures" / "mailbox"
GROUND_TRUTH = ROOT / "tests" / "expected.json"

SEED = 20260312


# --- attachment bodies ------------------------------------------------------
#
# Real files of each type, small and generated. A demo that ships .pdf files
# which are not PDFs is a demo with a hole in it exactly where a client would
# poke.


def make_pdf(title: str, lines: list[str]) -> bytes:
    """A genuine one-page PDF. Opens in any reader; no library needed."""
    text = "".join(
        f"BT /F1 11 Tf 56 {720 - 18 * i} Td ({_pdf_escape(line)}) Tj ET\n"
        for i, line in enumerate([title, "", *lines])
    )
    stream = text.encode("latin-1")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"
    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_at,
    )
    return bytes(out)


def _pdf_escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def make_png(width: int, height: int, colour: tuple[int, int, int]) -> bytes:
    """A genuine PNG of one flat colour, built with zlib and struct."""
    raw = b"".join(b"\x00" + bytes(colour) * width for _ in range(height))

    def chunk(kind: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + kind
            + payload
            + struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF)
        )

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def make_zip_document(entries: dict[str, str]) -> bytes:
    """What .xlsx and .docx are underneath: a zip with fixed timestamps."""
    import io
    import zipfile

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, body in entries.items():
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            archive.writestr(info, body)
    return buffer.getvalue()


def make_csv(header: list[str], rows: list[list[str]]) -> bytes:
    lines = [",".join(header), *[",".join(row) for row in rows]]
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


# --- the mailbox ------------------------------------------------------------


@dataclass
class Part:
    filename: str | None
    maintype: str
    subtype: str
    content: bytes
    broken_charset: bool = False


@dataclass
class Draft:
    key: str
    sender_name: str
    sender_email: str
    subject: str
    date: str | None
    body: str
    parts: list[Part] = field(default_factory=list)
    note: str = ""
    """Why this message is in the fixture. Copied into the ground truth so a
    reader of the test data knows which ones are load-bearing."""


def drafts() -> list[Draft]:
    rng = random.Random(SEED)

    def invoice_pdf(number: str, amount: str) -> bytes:
        return make_pdf(
            f"INVOICE {number}",
            [
                "Northgate Supplies Ltd (sample data)",
                "17 Fictional Way, Exampleton",
                "",
                f"Amount due: {amount}",
                "Terms: 30 days",
            ],
        )

    def photo(colour: tuple[int, int, int]) -> bytes:
        return make_png(96, 64, colour)

    items: list[Draft] = []

    def add(draft: Draft) -> None:
        items.append(draft)

    # -- the ordinary bulk: 20-odd messages that just file ------------------
    suppliers = [
        ("Northgate Supplies", "accounts@northgate-supplies.example"),
        ("Harborline Logistics", "billing@harborline-logistics.example"),
        ("Quayside Print", "hello@quayside-print.example"),
    ]
    for index, (name, address) in enumerate(suppliers):
        for step in range(3):
            number = f"1{index}{step}42"
            day = 3 + step * 9
            add(
                Draft(
                    key=f"invoice-{address.split('@')[1].split('.')[0]}-{number}",
                    sender_name=name,
                    sender_email=address,
                    subject=f"Invoice {number} for February",
                    date=f"Wed, {day:02d} Mar 2026 09:{12 + step * 7:02d}:00 +0000",
                    body="Invoice attached. Please remit by the due date.",
                    parts=[
                        Part(
                            f"invoice-{number}.pdf",
                            "application",
                            "pdf",
                            invoice_pdf(number, f"£{rng.randrange(120, 4200)}.00"),
                        )
                    ],
                )
            )

    for step in range(3):
        add(
            Draft(
                key=f"receipt-{step}",
                sender_name="Meadowlark Utilities",
                sender_email="noreply@meadowlark-utilities.example",
                subject=f"Receipt for payment received — account 88{step}1",
                date=f"Mon, {6 + step:02d} Apr 2026 07:30:00 +0000",
                body="Thank you. Your receipt is attached.",
                parts=[
                    Part(
                        f"receipt-88{step}1.pdf",
                        "application",
                        "pdf",
                        make_pdf(f"RECEIPT 88{step}1", ["Paid in full", "Sample data"]),
                    )
                ],
            )
        )

    for step in range(2):
        add(
            Draft(
                key=f"statement-{step}",
                sender_name="Northbank",
                sender_email="statements@northbank.example",
                subject=f"Your statement is ready — 0{step + 1} Feb 2026",
                date=f"Sun, 0{step + 1} Feb 2026 06:00:00 +0000",
                body="Your statement is attached.",
                parts=[
                    Part(
                        f"statement-2026-0{step + 1}.pdf",
                        "application",
                        "pdf",
                        make_pdf(
                            f"STATEMENT 2026-0{step + 1}",
                            ["Opening balance 0.00", "Closing balance 0.00", "Sample data"],
                        ),
                    )
                ],
            )
        )

    # The ordering demonstration: an invoice *from the bank*. `invoices` sits
    # above `bank-statements` in the rule file, so it wins.
    add(
        Draft(
            key="bank-invoice",
            sender_name="Northbank",
            sender_email="statements@northbank.example",
            subject="Invoice 4471 — account fees",
            date="Thu, 12 Feb 2026 11:05:00 +0000",
            body="Fee invoice attached.",
            parts=[
                Part("invoice-4471.pdf", "application", "pdf", make_pdf("INVOICE 4471", ["Sample"]))
            ],
            note="rule ordering: matches both `invoices` and `bank-statements`; invoices is first",
        )
    )

    for step in range(4):
        add(
            Draft(
                key=f"site-photo-{step}",
                sender_name="Sunfield Installations",
                sender_email="crew@sunfield-installations.example",
                subject=f"Site photos — job {4400 + step}",
                date=f"Fri, {13 + step:02d} Mar 2026 16:4{step}:00 +0000",
                body="Photos from today.",
                parts=[
                    Part(
                        f"job-{4400 + step}-{angle}.png",
                        "image",
                        "png",
                        photo((40 + step * 30, 90 + step * 20, 160 - step * 25)),
                    )
                    for angle in ("front", "rear")
                ],
                note="two attachments on one message; filed by extension under the sender",
            )
        )

    add(
        Draft(
            key="contract",
            sender_name="Jo Parkin",
            sender_email="jo.parkin@bellweather-signs.example",
            subject="As discussed",
            date="Tue, 24 Mar 2026 13:20:00 +0000",
            body="Signed copy attached.",
            parts=[
                Part(
                    "Bellweather-NDA-signed.pdf",
                    "application",
                    "pdf",
                    make_pdf("MUTUAL NDA", ["Between two invented companies", "Sample data"]),
                )
            ],
            note="matched on the attachment filename, not the subject",
        )
    )

    add(
        Draft(
            key="supplier-misc",
            sender_name="Northgate Supplies",
            sender_email="accounts@northgate-supplies.example",
            subject="Updated price list",
            date="Mon, 30 Mar 2026 10:00:00 +0000",
            body="New prices from April.",
            parts=[
                Part(
                    "price-list-april.xlsx",
                    "application",
                    "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    make_zip_document({"sample.txt": "synthetic price list"}),
                )
            ],
            note="falls through to the last rule, filed under the sender's domain",
        )
    )

    # A non-ASCII subject, to prove RFC 2047 decoding happens and that the
    # slug folds the umlaut instead of dropping it.
    add(
        Draft(
            key="umlaut",
            sender_name="Jürgen Falk",
            sender_email="j.falk@harborline-logistics.example",
            subject="Invoice 9931 — Rechnung März",
            date="Wed, 18 Mar 2026 08:15:00 +0000",
            body="Rechnung im Anhang.",
            parts=[
                Part(
                    "Rechnung-März-9931.pdf",
                    "application",
                    "pdf",
                    make_pdf("RECHNUNG 9931", ["Beispieldaten"]),
                )
            ],
            note="non-ASCII sender name, subject and filename",
        )
    )

    # -- the cases the README and the tests are about ----------------------

    # Collision: same sender, same day, same rule, same stem, different bytes.
    for step, amount in enumerate(("£410.00", "£1,980.00")):
        add(
            Draft(
                key=f"collision-{step}",
                sender_name="Harborline Logistics",
                sender_email="billing@harborline-logistics.example",
                subject="Invoice — March haulage",
                date="Wed, 25 Mar 2026 09:00:00 +0000",
                body="Invoice attached.",
                parts=[
                    Part(
                        "invoice.pdf",
                        "application",
                        "pdf",
                        make_pdf("INVOICE", [f"Amount due: {amount}", "Sample data"]),
                    )
                ],
                note="collision: identical destination name, different contents",
            )
        )

    add(
        Draft(
            key="no-filename",
            sender_name="Quayside Print",
            sender_email="hello@quayside-print.example",
            subject="Invoice 2210 — proof copy",
            date="Thu, 26 Mar 2026 15:00:00 +0000",
            body="Proof attached.",
            parts=[Part(None, "application", "pdf", make_pdf("PROOF", ["Sample data"]))],
            note="unparseable name: the part declares no filename at all",
        )
    )

    add(
        Draft(
            key="punctuation-filename",
            sender_name="Quayside Print",
            sender_email="hello@quayside-print.example",
            subject="Invoice 2211",
            date="Thu, 26 Mar 2026 15:30:00 +0000",
            body="Attached.",
            parts=[Part("….pdf", "application", "pdf", make_pdf("PROOF 2211", ["Sample data"]))],
            note="unparseable name: nothing in it survives slugifying",
        )
    )

    add(
        Draft(
            key="traversal-filename",
            sender_name="Harborline Logistics",
            sender_email="billing@harborline-logistics.example",
            subject="Invoice 7788 — notes",
            date="Fri, 27 Mar 2026 09:45:00 +0000",
            body="Notes attached.",
            parts=[
                Part(
                    "../../../etc/passwd-notes.txt",
                    "text",
                    "plain",
                    b"synthetic notes, nothing sensitive\r\n",
                )
            ],
            note="a filename carrying a path; only the last component is used",
        )
    )

    add(
        Draft(
            key="no-attachment",
            sender_name="Jo Parkin",
            sender_email="jo.parkin@bellweather-signs.example",
            subject="Re: the March schedule",
            date="Tue, 31 Mar 2026 12:00:00 +0000",
            body="Nothing attached, just confirming Thursday works.",
            parts=[],
            note="no attachment: gets an index row and nothing else",
        )
    )

    add(
        Draft(
            key="no-date",
            sender_name="Quayside Print",
            sender_email="hello@quayside-print.example",
            subject="Invoice 2212",
            date=None,
            body="Attached.",
            parts=[
                Part("invoice-2212.pdf", "application", "pdf", make_pdf("INVOICE 2212", ["Sample"]))
            ],
            note="no Date header: there is no year/month to file under, so unsorted",
        )
    )

    add(
        Draft(
            key="bad-date",
            sender_name="Meadowlark Utilities",
            sender_email="noreply@meadowlark-utilities.example",
            subject="Receipt — account 8841",
            date="Sometime last Tuesday",
            body="Attached.",
            parts=[
                Part("receipt-8841.pdf", "application", "pdf", make_pdf("RECEIPT 8841", ["Sample"]))
            ],
            note="unparseable Date header: same treatment as a missing one",
        )
    )

    add(
        Draft(
            key="broken-charset",
            sender_name="Jo Parkin",
            sender_email="jo.parkin@bellweather-signs.example",
            subject="Invoice 3120 — meeting notes",
            date="Wed, 01 Apr 2026 09:00:00 +0000",
            body="Notes attached.",
            parts=[
                Part(
                    "meeting-notes.txt",
                    "text",
                    "plain",
                    b"synthetic notes\r\n",
                    broken_charset=True,
                )
            ],
            note="the attachment declares a charset that does not exist, so it will not decode",
        )
    )

    for step, (subject, filename, body) in enumerate(
        [
            ("Lunch on Thursday?", "menu.csv", make_csv(["item", "price"], [["soup", "4.50"]])),
            (
                "Fwd: newsletter",
                "spring-newsletter.docx",
                make_zip_document({"sample.txt": "synthetic newsletter"}),
            ),
        ]
    ):
        add(
            Draft(
                key=f"unmatched-{step}",
                sender_name="Jo Parkin",
                sender_email="jo.parkin@bellweather-signs.example",
                subject=subject,
                date=f"Thu, 0{2 + step} Apr 2026 11:00:00 +0000",
                body="See attached.",
                parts=[Part(filename, *_types_for(filename), body)],
                note="no rule matches: goes to unsorted with the reason",
            )
        )

    return items


def _types_for(filename: str) -> tuple[str, str]:
    if filename.endswith(".csv"):
        return "text", "csv"
    if filename.endswith(".docx"):
        return "application", "vnd.openxmlformats-officedocument.wordprocessingml.document"
    return "application", "octet-stream"  # pragma: no cover - only two kinds here


def parseable(value: str | None) -> bool:
    if value is None:
        return False
    try:
        parsedate_to_datetime(value)
    except (TypeError, ValueError):
        return False
    return True


def build(draft: Draft, position: int) -> EmailMessage:
    message = EmailMessage()
    message["From"] = f"{draft.sender_name} <{draft.sender_email}>"
    message["To"] = "office@rookery-demo.example"
    message["Subject"] = draft.subject
    # A date the stdlib cannot parse cannot be *written* by the stdlib either:
    # `email.policy.default` serialises it as an empty `Date:` header, which
    # would make the bad-date fixture indistinguishable from the no-date one
    # and quietly stop testing anything. It is spliced in as raw bytes below
    # instead, which is how a mail client that emits rubbish would produce it.
    if parseable(draft.date):
        message["Date"] = draft.date
    message["Message-ID"] = f"<fixture-{position:03d}@rookery-demo.example>"
    message.set_content(draft.body + "\n")

    for part in draft.parts:
        kwargs = {"maintype": part.maintype, "subtype": part.subtype}
        if part.filename is not None:
            kwargs["filename"] = part.filename
        message.add_attachment(part.content, **kwargs)

    if draft.parts:
        # add_attachment picks a random boundary, which would make every
        # regeneration a diff. Fixing it keeps `make fixtures` a no-op.
        message.set_boundary(f"=-fixture-{position:03d}-=")
    for part, built in zip(draft.parts, message.iter_attachments()):
        if part.broken_charset:
            built.set_param("charset", "x-unknown-9000")
    return message


def main() -> int:
    MAILBOX.mkdir(parents=True, exist_ok=True)
    for stale in MAILBOX.glob("*.eml"):
        stale.unlink()

    items = drafts()
    truth = {
        "generated_by": "fixtures/generate_mailbox.py",
        "seed": SEED,
        "messages": [],
    }

    for position, draft in enumerate(items, start=1):
        message = build(draft, position)
        name = f"{position:03d}-{draft.key}.eml"
        data = message.as_bytes(policy=email.policy.SMTP)
        if draft.date is not None and not parseable(draft.date):
            data = b"Date: " + draft.date.encode("ascii") + b"\r\n" + data
        (MAILBOX / name).write_bytes(data)
        truth["messages"].append(
            {
                "file": name,
                "sender_name": draft.sender_name,
                "sender_email": draft.sender_email,
                "subject": draft.subject,
                "date": draft.date,
                "note": draft.note,
                "attachments": [
                    {
                        "declared_filename": part.filename,
                        "content_type": f"{part.maintype}/{part.subtype}",
                        "size": len(part.content),
                        "sha256": hashlib.sha256(part.content).hexdigest(),
                        "decodable": not part.broken_charset,
                    }
                    for part in draft.parts
                ],
            }
        )

    GROUND_TRUTH.parent.mkdir(parents=True, exist_ok=True)
    GROUND_TRUTH.write_text(json.dumps(truth, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    attachments = sum(len(m["attachments"]) for m in truth["messages"])
    print(f"wrote {len(items)} messages ({attachments} attachments) to {MAILBOX}")
    print(f"wrote ground truth to {GROUND_TRUTH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
